import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Header from "./components/Header"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
            <div className="main container mx-auto">
                <div className="flex items-start justify-center min-height">
                  <div className="mt-10">{children}</div>
                </div>
            </div>          
          </body>
      </html>
    </ClerkProvider>
  )
}
